# Generated by Django 6.0.3 on 2026-07-07 09:38

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


LEGACY_CARESEEKER_EQUIPMENT = (
    ("catheter", "Catheter"),
    ("g_tube", "G-tube"),
    ("colostomy_bag", "Colostomy bag"),
    ("trachea_tube", "Trachea tube"),
    ("diapers", "Diapers"),
    ("bed_pads", "Bed pads"),
    ("bedside_commode", "Bedside commode"),
    ("oxygen", "Oxygen"),
    ("none", "None"),
)


def reset_pk_sequence(schema_editor, table_name):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            (
                "SELECT setval("
                "pg_get_serial_sequence(%s, 'id'), "
                "COALESCE(MAX(id), 1), "
                "MAX(id) IS NOT NULL"
                f") FROM {table_name}"
            ),
            [table_name],
        )


def populate_shared_lookups(apps, schema_editor):
    Condition = apps.get_model("utils", "Condition")
    Equipment = apps.get_model("utils", "Equipment")
    LegacyCondition = apps.get_model("careseekers", "Condition")
    LegacyExperienceItem = apps.get_model("caregivers", "CaregiverExperienceItem")

    for row in LegacyCondition.objects.all():
        Condition.objects.update_or_create(
            id=row.id,
            defaults={
                "name": row.name,
                "slug": row.slug,
                "is_active": row.is_active,
                "created_at": row.created_at,
                "updated_at": row.updated_at,
                "created_by_id": row.created_by_id,
            },
        )

    next_condition_id = (
        Condition.objects.order_by("-id").values_list("id", flat=True).first() or 0
    )
    for row in LegacyExperienceItem.objects.filter(item_type="condition"):
        existing = Condition.objects.filter(slug=row.slug).first()
        if existing:
            existing.name = row.name
            existing.is_active = row.is_active
            existing.created_by_id = row.created_by_id
            existing.save(
                update_fields=["name", "is_active", "created_by", "updated_at"]
            )
            continue

        next_condition_id += 1
        Condition.objects.create(
            id=next_condition_id,
            name=row.name,
            slug=row.slug,
            is_active=row.is_active,
            created_by_id=row.created_by_id,
        )

    next_equipment_id = (
        Equipment.objects.order_by("-id").values_list("id", flat=True).first() or 0
    )
    for row in LegacyExperienceItem.objects.filter(item_type="equipment"):
        existing = Equipment.objects.filter(slug=row.slug).first()
        if existing:
            existing.name = row.name
            existing.is_active = row.is_active
            existing.created_by_id = row.created_by_id
            existing.save(
                update_fields=["name", "is_active", "created_by", "updated_at"]
            )
            continue

        next_equipment_id += 1
        Equipment.objects.create(
            id=next_equipment_id,
            name=row.name,
            slug=row.slug,
            is_active=row.is_active,
            created_by_id=row.created_by_id,
        )

    for slug, name in LEGACY_CARESEEKER_EQUIPMENT:
        existing = Equipment.objects.filter(slug=slug).first()
        if existing:
            existing.name = name
            existing.is_active = True
            existing.save(update_fields=["name", "is_active", "updated_at"])
            continue

        next_equipment_id += 1
        Equipment.objects.create(
            id=next_equipment_id,
            name=name,
            slug=slug,
            is_active=True,
        )

    reset_pk_sequence(schema_editor, "utils_condition")
    reset_pk_sequence(schema_editor, "utils_equipment")


def reverse_populate_shared_lookups(apps, schema_editor):
    apps.get_model("utils", "Condition").objects.all().delete()
    apps.get_model("utils", "Equipment").objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caregivers', '0010_qualifications_experience'),
        ('careseekers', '0006_careseeker_care_needs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.RunPython(
            populate_shared_lookups,
            reverse_populate_shared_lookups,
        ),
    ]
