# Generated by Django 6.0.3 on 2026-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0002_skill_caregiverskill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caregiver",
            name="hourly_rate_cents",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="caregiver",
            name="years_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
