# Generated by Django 6.0.3 on 2026-05-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0004_alter_caregiver_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='availability',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
