# Generated by Django 6.0.3 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0006_caregiverservice_caregiver_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiver",
            name="onboarding_resume",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
