# Generated by Django 6.0.3 on 2026-06-10 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0007_caregiver_onboarding_resume"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiver",
            name="checkr_candidate_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="ScreeningOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="usd", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("payment_required", "Payment required"),
                            ("payment_authorized", "Payment authorized"),
                            ("checkr_invited", "Checkr invited"),
                            ("checkr_completed", "Checkr completed"),
                            ("payment_captured", "Payment captured"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="payment_required",
                        max_length=32,
                    ),
                ),
                ("invitation_url", models.URLField(blank=True, null=True)),
                (
                    "checkr_invitation_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_orders",
                        to="caregivers.caregiver",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screening_order",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="caregivers__status_be1c02_idx"
                    ),
                    models.Index(
                        fields=["checkr_invitation_id"],
                        name="caregivers__checkr__10b913_idx",
                    ),
                ],
            },
        ),
    ]
