# Generated by Codex on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0008_caregiver_checkr_candidate_id_screeningorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiver",
            name="screening_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("payment_authorized", "Payment authorized"),
                    ("checkr_invited", "Checkr invited"),
                    ("checkr_in_progress", "Checkr in progress"),
                    ("approved", "Approved"),
                    ("review_required", "Review required"),
                    ("rejected", "Rejected"),
                ],
                default="not_started",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("review_required", "Review required"),
                    ("in_review", "In review"),
                    ("onboarding_in_progress", "Onboarding in progress"),
                ],
                default="onboarding_in_progress",
                max_length=32,
            ),
        ),
    ]
