# Generated by Codex on 2026-07-06

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


CERTIFICATIONS = [
    ("CNA", "cna"),
    ("HCA ID", "hca-id"),
    ("CPR/First Aid", "cpr-first-aid"),
    ("Certified Medicine Aide", "certified-medicine-aide"),
    ("RN", "rn"),
    ("LVN", "lvn"),
    ("TB Clearance", "tb-clearance"),
    ("Live Scan", "live-scan"),
]

EXPERIENCE_ITEMS = [
    ("Alzheimer's", "alzheimers", "condition"),
    ("Dementia", "dementia", "condition"),
    ("Parkinson's", "parkinsons", "condition"),
    ("Stroke", "stroke", "condition"),
    ("Hospice", "hospice", "condition"),
    ("Hip/knee surgery", "hip_knee_surgery", "condition"),
    ("Blind/deaf patient", "blind_deaf_patient", "condition"),
    ("Paralysis/quadriplegia", "paralysis_quadriplegia", "condition"),
    ("G-tube", "g_tube", "condition"),
    ("Wound care", "wound_care", "condition"),
    ("Catheter bag", "catheter_bag", "condition"),
    ("Colostomy bag", "colostomy_bag", "condition"),
    ("Commode", "commode", "equipment"),
    ("Hospital bed", "hospital_bed", "equipment"),
    ("Shower chair", "shower_chair", "equipment"),
    ("Walker", "walker", "equipment"),
    ("Cane", "cane", "equipment"),
    ("Wheelchair", "wheelchair", "equipment"),
    ("Gait belt", "gait_belt", "equipment"),
    ("Hoyer lift", "hoyer_lift", "equipment"),
    ("Oxygen machine", "oxygen_machine", "equipment"),
]


def seed_qualifications(apps, schema_editor):
    Certification = apps.get_model("caregivers", "Certification")
    CaregiverExperienceItem = apps.get_model("caregivers", "CaregiverExperienceItem")

    for name, slug in CERTIFICATIONS:
        Certification.objects.update_or_create(
            slug=slug,
            defaults={"name": name, "is_active": True},
        )

    for name, slug, item_type in EXPERIENCE_ITEMS:
        CaregiverExperienceItem.objects.update_or_create(
            slug=slug,
            defaults={"name": name, "item_type": item_type, "is_active": True},
        )


def unseed_qualifications(apps, schema_editor):
    Certification = apps.get_model("caregivers", "Certification")
    CaregiverExperienceItem = apps.get_model("caregivers", "CaregiverExperienceItem")

    Certification.objects.filter(slug__in=[slug for _, slug in CERTIFICATIONS]).delete()
    CaregiverExperienceItem.objects.filter(
        slug__in=[slug for _, slug, _ in EXPERIENCE_ITEMS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0009_caregiver_account_screening_statuses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiver",
            name="has_auto_insurance_registration",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="has_car",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="has_drivers_license",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="pet_types_comfortable",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="transportation_comfort",
            field=models.CharField(
                blank=True,
                choices=[
                    ("can_drive_client", "Can drive client"),
                    ("errands_only", "Errands only"),
                    ("no_transportation", "No transportation"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="willing_with_pets",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="willing_with_smokers",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaregiverExperienceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("condition", "Condition"), ("equipment", "Equipment")],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaregiverCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("self_reported", "Self reported"),
                            ("pending_review", "Pending review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="self_reported",
                        max_length=32,
                    ),
                ),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="caregiver_certifications/",
                    ),
                ),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_certifications",
                        to="caregivers.caregiver",
                    ),
                ),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_certifications",
                        to="caregivers.certification",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("caregiver", "certification")},
            },
        ),
        migrations.CreateModel(
            name="CaregiverExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("no_experience", "No experience"),
                            ("some_experience", "Some experience"),
                            ("good_experience", "Good experience"),
                            ("excellent_experience", "Excellent experience"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_experiences",
                        to="caregivers.caregiver",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_experiences",
                        to="caregivers.caregiverexperienceitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("caregiver", "item")},
            },
        ),
        migrations.RunPython(seed_qualifications, unseed_qualifications),
    ]
