# Generated by Django 6.0.3 on 2026-07-07 09:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_caregiver_experience(apps, schema_editor):
    CaregiverExperience = apps.get_model("caregivers", "CaregiverExperience")
    CaregiverCondition = apps.get_model("caregivers", "CaregiverCondition")
    CaregiverEquipment = apps.get_model("caregivers", "CaregiverEquipment")
    Condition = apps.get_model("utils", "Condition")
    Equipment = apps.get_model("utils", "Equipment")

    condition_ids_by_slug = {
        row.slug: row.id for row in Condition.objects.filter(is_active=True)
    }
    equipment_ids_by_slug = {
        row.slug: row.id for row in Equipment.objects.filter(is_active=True)
    }

    for row in CaregiverExperience.objects.select_related("item"):
        item_slug = row.item.slug
        if row.item.item_type == "condition":
            condition_id = condition_ids_by_slug.get(item_slug)
            if condition_id:
                CaregiverCondition.objects.update_or_create(
                    caregiver_id=row.caregiver_id,
                    condition_id=condition_id,
                    defaults={
                        "skill_level": row.skill_level,
                        "created_by_id": row.created_by_id,
                    },
                )
        elif row.item.item_type == "equipment":
            equipment_id = equipment_ids_by_slug.get(item_slug)
            if equipment_id:
                CaregiverEquipment.objects.update_or_create(
                    caregiver_id=row.caregiver_id,
                    equipment_id=equipment_id,
                    defaults={
                        "skill_level": row.skill_level,
                        "created_by_id": row.created_by_id,
                    },
                )


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0010_qualifications_experience'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_level', models.CharField(choices=[('no_experience', 'No experience'), ('some_experience', 'Some experience'), ('good_experience', 'Good experience'), ('excellent_experience', 'Excellent experience')], max_length=32)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_conditions', to='caregivers.caregiver')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_conditions', to='utils.condition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('caregiver', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='CaregiverEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_level', models.CharField(choices=[('no_experience', 'No experience'), ('some_experience', 'Some experience'), ('good_experience', 'Good experience'), ('excellent_experience', 'Excellent experience')], max_length=32)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_equipments', to='caregivers.caregiver')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_equipments', to='utils.equipment')),
            ],
            options={
                'unique_together': {('caregiver', 'equipment')},
            },
        ),
        migrations.RunPython(
            migrate_caregiver_experience,
            migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='CaregiverExperience',
        ),
        migrations.DeleteModel(
            name='CaregiverExperienceItem',
        ),
    ]
