# Generated by Codex on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("checkout_started", "Checkout started"),
                    ("authorized", "Authorized"),
                    ("capture_pending", "Capture pending"),
                    ("captured", "Captured"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=32,
            ),
        ),
    ]
