# Generated by Django 6.0.3 on 2026-04-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_useraddress_address_useraddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('provider', 'Provider')], default='customer', max_length=50),
        ),
    ]
