# Generated by Django 6.0.3 on 2026-04-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_role_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_type',
        ),
    ]
