# Generated by Codex on 2026-04-10

from django.db import migrations


def seed_default_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    default_roles = ["staff", "superuser", "caregiver", "careseeker"]

    for code in default_roles:
        Role.objects.get_or_create(code=code)


def unseed_default_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    default_roles = ["staff", "superuser", "caregiver", "careseeker"]
    Role.objects.filter(code__in=default_roles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_role_type"),
    ]

    operations = [
        migrations.RunPython(seed_default_roles, unseed_default_roles),
    ]

