# Generated by Django 6.0.3 on 2026-05-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_name',
        ),
    ]
