# Generated by Django 6.0.3 on 2026-06-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_userprofile_preferred_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
