# Generated by Django 6.0.3 on 2026-06-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_ethnicity'),
        ('users', '0015_user_phone_verification_fields'),
    ]

    operations = [
    ]
