# Generated by Django 6.0.3 on 2026-06-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_languages'),
        ('users', '0016_merge_20260623_1418'),
    ]

    operations = [
    ]
