# Generated by Django 6.0.3 on 2026-04-09 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_address_useraddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Careseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField(null=True)),
                ('careseeker_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careseeker_profile', to=settings.AUTH_USER_MODEL)),
                ('primary_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careseeker_primary_address', to='users.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
