# Generated by Django 6.0.3 on 2026-04-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careseekers', '0001_initial'),
        ('users', '0004_address_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careseeker',
            name='primary_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for', to='users.useraddress'),
        ),
    ]
