# Generated by Django 6.0.3 on 2026-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careseekers', '0004_careseeker_onboarding_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='careseeker',
            name='account_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('review_required', 'Review required'), ('in_review', 'In review'), ('onboarding_in_progress', 'Onboarding in progress')], default='onboarding_in_progress', max_length=32),
        ),
    ]
