# Generated by Django 6.0.3 on 2026-07-07 09:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_careseeker_equipment(apps, schema_editor):
    Careseeker = apps.get_model("careseekers", "Careseeker")
    CareseekerEquipment = apps.get_model("careseekers", "CareseekerEquipment")
    Equipment = apps.get_model("utils", "Equipment")

    equipment_by_slug = {
        row.slug: row.id for row in Equipment.objects.filter(is_active=True)
    }

    for careseeker in Careseeker.objects.exclude(medical_equipment=[]):
        values = (
            careseeker.medical_equipment
            if isinstance(careseeker.medical_equipment, list)
            else []
        )
        for slug in values:
            equipment_id = equipment_by_slug.get(str(slug))
            if equipment_id:
                CareseekerEquipment.objects.get_or_create(
                    careseeker_id=careseeker.id,
                    equipment_id=equipment_id,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('careseekers', '0006_careseeker_care_needs'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareseekerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('careseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careseeker_equipments', to='careseekers.careseeker')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careseeker_equipments', to='utils.equipment')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('careseeker', 'equipment')},
            },
        ),
        migrations.RunPython(
            migrate_careseeker_equipment,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='careseekercondition',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careseeker_conditions', to='utils.condition'),
        ),
        migrations.RemoveField(
            model_name='careseeker',
            name='medical_equipment',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
