# Generated by Django 6.0.3 on 2026-04-09 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caregivers', '0002_skill_caregiverskill'),
        ('careseekers', '0002_alter_careseeker_primary_address'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('no_show', 'No Show')], db_index=True, max_length=20)),
                ('application_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_application', to='marketplace.jobapplication')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_caregiver', to='caregivers.caregiver')),
                ('careseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_careseeker', to='careseekers.careseeker')),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_job_post', to='marketplace.jobpost')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
