# Generated by Django 6.0.3 on 2026-04-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='application_id',
            new_name='application',
        ),
    ]
